# -*- coding: utf-8 -*-
"""
游戏汉化工具 - Unity 部分
给 Unity 游戏装 BepInEx + XUnity.AutoTranslator 插件，插件把游戏里出现的文字发给本工具，
本工具用你自己的 API 翻译后返回（边玩边翻）。翻过的会存下来，下次不再花钱。
"""
import datetime
import json
import os
import re
import shutil
import struct
import subprocess
import threading
import time
import urllib.parse
import urllib.request
import zipfile
from http.server import BaseHTTPRequestHandler, HTTPServer
from socketserver import ThreadingMixIn

import cn_core as core

PORT = 47811
LANG = "zh-CN"

BEPINEX = {
    ("Mono", "x64"): "https://github.com/BepInEx/BepInEx/releases/download/v5.4.23.5/BepInEx_win_x64_5.4.23.5.zip",
    ("Mono", "x86"): "https://github.com/BepInEx/BepInEx/releases/download/v5.4.23.5/BepInEx_win_x86_5.4.23.5.zip",
    ("IL2CPP", "x64"): "https://github.com/BepInEx/BepInEx/releases/download/v6.0.0-pre.2/BepInEx-Unity.IL2CPP-win-x64-6.0.0-pre.2.zip",
    ("IL2CPP", "x86"): "https://github.com/BepInEx/BepInEx/releases/download/v6.0.0-pre.2/BepInEx-Unity.IL2CPP-win-x86-6.0.0-pre.2.zip",
}
XUNITY = {
    "Mono": "https://github.com/bbepis/XUnity.AutoTranslator/releases/download/v5.6.2/XUnity.AutoTranslator-BepInEx-5.6.2.zip",
    "IL2CPP": "https://github.com/bbepis/XUnity.AutoTranslator/releases/download/v5.6.2/XUnity.AutoTranslator-BepInEx-IL2CPP-5.6.2.zip",
}
DOWNLOAD_DIR = os.path.join(core.TOOL_DIR, "downloads")
CACHE_PATH = os.path.join(core.DATA_DIR, "unity_cache.zh.json")
META_PATH = os.path.join(core.DATA_DIR, "unity_cache.meta.json")

FROM_LANGS = [("英语", "en"), ("日语", "ja"), ("韩语", "ko"), ("俄语", "ru"), ("简体以外的中文", "zh-TW")]


# ============================================================== 识别 Unity 游戏

def data_dir(root):
    try:
        names = sorted(os.listdir(root))
    except OSError:
        return None
    for d in names:
        if d.endswith("_Data") and os.path.isdir(os.path.join(root, d)) and os.path.isfile(os.path.join(root, d[:-5] + ".exe")):
            return d
    return None


def is_unity_root(root):
    d = data_dir(root)
    if not d:
        return False
    dp = os.path.join(root, d)
    return (os.path.isfile(os.path.join(root, "UnityPlayer.dll"))
            or any(os.path.exists(os.path.join(dp, x)) for x in ("globalgamemanagers", "mainData", "data.unity3d", "Managed", "il2cpp_data")))


def pe_arch(path):
    try:
        with open(path, "rb") as f:
            f.seek(0x3C)
            off = struct.unpack("<I", f.read(4))[0]
            f.seek(off)
            if f.read(4) != b"PE\0\0":
                return "x64"
            machine = struct.unpack("<H", f.read(2))[0]
        return "x86" if machine == 0x14C else "x64"
    except Exception:
        return "x64"


def unity_version(root, d):
    dp = os.path.join(root, d)
    for fn in ("globalgamemanagers", "mainData", "data.unity3d"):
        p = os.path.join(dp, fn)
        if os.path.isfile(p):
            try:
                with open(p, "rb") as f:
                    head = f.read(4096)
                m = re.search(rb"((?:20\d\d|6000|[45]\.\d)\.\d+\.\d+[abfpx]\d+)", head)
                if m:
                    return m.group(1).decode("ascii")
            except Exception:
                pass
    return "?"


def unity_info(root):
    d = data_dir(root)
    if not d:
        return None
    name = d[:-5]
    exe = os.path.join(root, name + ".exe")
    backend = "IL2CPP" if os.path.isfile(os.path.join(root, "GameAssembly.dll")) else "Mono"
    arch_src = os.path.join(root, "UnityPlayer.dll") if os.path.isfile(os.path.join(root, "UnityPlayer.dll")) else exe
    return {"title": name, "exe": exe, "data": d, "backend": backend,
            "arch": pe_arch(arch_src), "version": unity_version(root, d)}


# ============================================================== 安装 / 卸载插件

def bepinex_present(root):
    core_dir = os.path.join(root, "BepInEx", "core")
    return any(os.path.isfile(os.path.join(core_dir, x)) for x in ("BepInEx.dll", "BepInEx.Core.dll"))


def xunity_present(root):
    return os.path.isdir(os.path.join(root, "BepInEx", "plugins", "XUnity.AutoTranslator"))


def config_path(root):
    return os.path.join(root, "BepInEx", "config", "AutoTranslatorConfig.ini")


def translation_file(root):
    return os.path.join(root, "BepInEx", "Translation", LANG, "Text", "_AutoGeneratedTranslations.txt")


def download(url, log, stop):
    os.makedirs(DOWNLOAD_DIR, exist_ok=True)
    fn = url.rsplit("/", 1)[1]
    p = os.path.join(DOWNLOAD_DIR, fn)
    if os.path.isfile(p) and os.path.getsize(p) > 0:
        return p
    log("  下载 %s ……" % fn)
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    try:
        with urllib.request.urlopen(req, timeout=60, context=core.SSL_CTX) as r, open(p + ".part", "wb") as f:
            total = int(r.headers.get("Content-Length") or 0)
            got, last = 0, 0
            while True:
                if stop is not None and stop.is_set():
                    raise core.StopRequested()
                chunk = r.read(256 * 1024)
                if not chunk:
                    break
                f.write(chunk)
                got += len(chunk)
                if got - last >= 5 * 1024 * 1024:
                    last = got
                    log("    已下载 %.1f / %.1f MB" % (got / 1048576.0, total / 1048576.0))
    except core.StopRequested:
        raise
    except Exception as e:
        try:
            os.remove(p + ".part")
        except OSError:
            pass
        raise RuntimeError("从 GitHub 下载 %s 失败（%s）。GitHub 连不上的话，开一下代理再试。" % (fn, e))
    os.replace(p + ".part", p)
    return p


def _extract_new(zip_path, root, created):
    """解压到游戏目录，已经存在的文件一律不覆盖；记录新建了哪些文件"""
    root_abs = os.path.abspath(root)
    with zipfile.ZipFile(zip_path) as z:
        for info in z.infolist():
            name = info.filename.replace("\\", "/")
            if name.endswith("/"):
                continue
            if name.lower().endswith(".md") and "/" in name and name.split("/")[-2] == "plugins":
                continue  # 插件自带的说明文件，不需要
            target = os.path.abspath(os.path.join(root, name))
            if not target.startswith(root_abs + os.sep):
                continue
            if os.path.exists(target):
                continue
            os.makedirs(os.path.dirname(target), exist_ok=True)
            with z.open(info) as src, open(target, "wb") as dst:
                shutil.copyfileobj(src, dst)
            created.append(os.path.relpath(target, root_abs).replace("\\", "/"))


def _write_ini(path, settings):
    """只改我们管的几个键，其他内容原样保留"""
    lines = []
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8-sig", errors="replace") as f:
            lines = f.read().splitlines()
    pending = {sec: dict(kv) for sec, kv in settings.items()}
    out, sec = [], None

    def flush(section):
        for k, v in pending.get(section, {}).items():
            out.append("%s=%s" % (k, v))
        pending[section] = {}

    for line in lines:
        m = re.match(r"\s*\[(.+?)\]\s*$", line)
        if m:
            if sec is not None:
                flush(sec)
            sec = m.group(1)
            out.append(line)
            continue
        m = re.match(r"\s*([^=;#\s][^=]*?)\s*=", line)
        if m and sec in pending and m.group(1) in pending[sec]:
            k = m.group(1)
            out.append("%s=%s" % (k, pending[sec].pop(k)))
            continue
        out.append(line)
    if sec is not None:
        flush(sec)
    for s, kv in pending.items():
        if kv:
            out.append("")
            out.append("[%s]" % s)
            for k, v in kv.items():
                out.append("%s=%s" % (k, v))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")


def write_config(root, cfg):
    family = core.font_family(cfg)
    _write_ini(config_path(root), {
        "Service": {"Endpoint": "CustomTranslate", "FallbackEndpoint": ""},
        "General": {"Language": LANG, "FromLanguage": cfg.get("unity_from_lang") or "en"},
        "Custom": {"Url": "http://127.0.0.1:%d/translate" % PORT},
        "Behaviour": {
            "MaxCharactersPerTranslation": "1000",
            "OverrideFont": family if cfg.get("unity_force_font") else "",
            "FallbackFontTextMeshPro": family,
        },
    })


def install(root, cfg, log, stop):
    info = unity_info(root)
    if not info:
        raise RuntimeError("这不像是一个 Unity 游戏目录")
    log("  Unity %s，%s，%s" % (info["version"], info["backend"], info["arch"]))
    man_path = core._data_path(root, "unity_manifest")
    man = core.read_json(man_path, None) or {"created": [], "bepinex_by_tool": False}
    created = man["created"]
    had_manifest = os.path.isfile(man_path)
    try:
        if not bepinex_present(root):
            zp = download(BEPINEX[(info["backend"], info["arch"])], log, stop)
            log("  安装 BepInEx（插件加载器）")
            man["bepinex_by_tool"] = True
            _extract_new(zp, root, created)
        else:
            log("  游戏里已经有 BepInEx，直接用")
        if not xunity_present(root):
            zp = download(XUNITY[info["backend"]], log, stop)
            log("  安装 XUnity.AutoTranslator（翻译插件）")
            _extract_new(zp, root, created)
        cfg_existed = os.path.isfile(config_path(root))
        write_config(root, cfg)
        if not cfg_existed and "BepInEx/config/AutoTranslatorConfig.ini" not in created:
            created.append("BepInEx/config/AutoTranslatorConfig.ini")
    finally:
        # 装到一半失败也把已经放进去的文件记下来，「还原」才删得干净
        if created or had_manifest:
            core.write_json(man_path, man, indent=1)
    if info["backend"] == "IL2CPP":
        log("  这是 IL2CPP 游戏：第一次启动会多等一两分钟（插件在做准备），之后就正常了。")
    return info


# BepInEx 运行后自己生成的东西（只有 BepInEx 是我们装的时候才清）
_GENERATED = ["BepInEx/cache", "BepInEx/interop", "BepInEx/unity-libs", "BepInEx/LogOutput.log",
              "BepInEx/LogOutput.log.1", "BepInEx/ErrorLog.log", "BepInEx/config/BepInEx.cfg",
              "BepInEx/Translation", "BepInEx/config/AutoTranslatorConfig.ini"]


def _prune_empty(root, rel_dir):
    """从里往外删空文件夹，有东西的不动"""
    d = os.path.join(root, rel_dir)
    for dirpath, dirnames, filenames in sorted(os.walk(d, topdown=False), key=lambda x: -len(x[0])):
        try:
            if not os.listdir(dirpath):
                os.rmdir(dirpath)
        except OSError:
            pass


_XUNITY_DIRS = ("BepInEx/plugins/XUnity.AutoTranslator/", "BepInEx/plugins/XUnity.ResourceRedirector/")


def _is_xunity_file(rel):
    """翻译插件自己的文件（其余的是 BepInEx 加载器）"""
    return (rel.startswith(_XUNITY_DIRS) or os.path.basename(rel).startswith("XUnity.")
            or rel == "BepInEx/config/AutoTranslatorConfig.ini")


def _foreign_mods(root, created):
    """BepInEx 里不是这个工具装的 mod 文件（plugins / patchers 里多出来的）"""
    mine = set(created)
    found = []
    for sub in ("BepInEx/plugins", "BepInEx/patchers"):
        for dirpath, dirnames, filenames in os.walk(os.path.join(root, sub)):
            for fn in filenames:
                rel = os.path.relpath(os.path.join(dirpath, fn), root).replace("\\", "/")
                if rel not in mine and not rel.startswith(_XUNITY_DIRS):
                    found.append(rel)
    return found


def remove(root, log):
    """只删这个工具装进去的文件；游戏里原来就有、或者你后来自己加的 mod 都不动。
    返回 None：不是这个工具装的；"removed"：拿掉了（BepInEx 是工具装的话也一起拿掉，恢复原版）；
    "kept_loader"：BepInEx 里有你别的 mod，只拿掉翻译插件，加载器留着；"partial"：有文件删不掉（游戏多半还开着）"""
    man_path = core._data_path(root, "unity_manifest")
    man = core.read_json(man_path, None)
    if not man:
        return None
    created = list(man.get("created", []))
    by_tool = bool(man.get("bepinex_by_tool"))
    foreign = _foreign_mods(root, created) if by_tool else []
    full = by_tool and not foreign
    targets = created if full else [rel for rel in created if _is_xunity_file(rel)]
    kept = [rel for rel in created if rel not in set(targets)]
    remaining = []
    for rel in targets:
        p = os.path.join(root, rel)
        try:
            if os.path.isfile(p):
                os.remove(p)
        except OSError as e:
            remaining.append(rel)
            if len(remaining) <= 3:
                log("  删不掉 %s（%s）" % (rel, e))
    if full and not remaining:
        for rel in _GENERATED:
            p = os.path.join(root, rel)
            if os.path.isdir(p):
                shutil.rmtree(p, ignore_errors=True)
            elif os.path.isfile(p):
                try:
                    os.remove(p)
                except OSError:
                    pass
    for d in ("BepInEx", "dotnet"):
        if os.path.isdir(os.path.join(root, d)):
            _prune_empty(root, d)
    if remaining or kept:
        # 清单留着：删不掉的下次再删；留下的加载器以后你删了别的 mod，再点「还原」能一起清掉
        man["created"] = remaining + kept
        core.write_json(man_path, man, indent=1)
    else:
        try:
            os.remove(man_path)
        except OSError:
            pass
    if remaining:
        return "partial"
    if kept and foreign:
        log("  BepInEx 里有别的 mod（例如 %s），插件加载器留着没删，不然那些 mod 会失效"
            % "、".join(foreign[:3]))
        return "kept_loader"
    return "removed"


def translated_count(root):
    p = translation_file(root)
    n = 0
    try:
        with open(p, "r", encoding="utf-8-sig", errors="replace") as f:
            for line in f:
                if "=" in line and not line.startswith("//"):
                    n += 1
    except OSError:
        pass
    return n


def status(root):
    info = unity_info(root)
    if not info:
        return {"error": "找不到这个游戏了（被移动或删除）"}
    return {"kind": "unity", "title": info["title"], "version": "Unity %s %s" % (info["version"].split("f")[0], info["backend"]),
            "installed": xunity_present(root), "done": translated_count(root)}


def launch(exe, root, args=()):
    subprocess.Popen([exe] + list(args), cwd=root)


# ============================================================== 本地翻译服务（插件把文字发到这里）

UNITY_TOKEN_RE = re.compile(r"<[^<>\n]{1,80}>|\{\{[^{}]*\}\}|\{\d+(?:,-?\d+)?(?::[^{}]*)?\}")

UNITY_PROMPT = """你是资深游戏本地化译者。把用户发来的这段游戏文本翻译成简体中文。
只输出译文本身：不要加引号、解释、注释或任何多余内容。
<...> 形式的富文本标签、{{A}} 和 {0} 这类占位符必须原样保留，不要翻译、不要删。
保留原文的换行。人名、地名用常见音译。语气口语化，保留原文的情绪和粗口程度；界面按钮类短词用中文游戏里的常见说法。
%s"""

_SAME_RULE = {
    # 原文是日语 / 繁体时，不能叫模型「是中文就原样输出」，不然只有汉字的日文、繁体字都会原样回来
    "ja": "原文是日语：只有汉字的日文词句也要翻成简体中文（如「開始」→「开始」）。只是数字/符号/代码的原样输出。",
    "zh-TW": "原文是繁体中文：转成简体中文，并换成中国大陆的常用说法。只是数字/符号/代码的原样输出。",
}
_DEFAULT_SAME_RULE = "如果原文已经是简体中文、或者只是数字/符号/代码，原样输出。"

_HANGUL_RE = re.compile(r"[ᄀ-ᇿ㄰-㆏가-힯]")
_HAN_KANA_RE = re.compile(r"[぀-ヿ㐀-䶿一-鿿豈-﫿]")


def need_translate(text, src_lang):
    """Ren'Py 那套判断只认拉丁/西里尔字母和假名；Unity 按你选的原文语言再补上韩文、纯汉字"""
    if core.need_translate(text):
        return True
    t = text.strip()
    if not t or len(t) > 5000:
        return False
    bare = UNITY_TOKEN_RE.sub("", t)
    if src_lang == "ko":
        return bool(_HANGUL_RE.search(bare))
    if src_lang in ("ja", "zh-TW"):
        return bool(_HAN_KANA_RE.search(bare))
    return False


class _Server(ThreadingMixIn, HTTPServer):
    daemon_threads = True
    allow_reuse_address = True


class TranslateService(object):
    def __init__(self, cfg, log):
        self.cfg = cfg  # 和界面共用同一个 dict，改设置立刻生效
        self.log = log
        self.usage = core.Usage()
        self.lock = threading.Lock()
        self.file_lock = threading.Lock()  # 存盘、删除都排队写，旧快照不会盖掉新内容
        self.broken = None
        try:
            self.cache = core.read_json(CACHE_PATH, {}) or {}
            self.meta = core.read_json(META_PATH, {}) or {}
        except core.DataFileError as e:
            # 缓存文件坏了：不能当空的用，不然自动保存会把它盖掉、翻过的又要重新花钱
            self.cache, self.meta = {}, {}
            self.broken = str(e)
            log("Unity 翻译缓存读不了，Unity 边玩边翻先停用：%s" % e)
        self.dirty = 0
        self.count = 0
        self.failed = 0
        self.current_game = ""
        self.stop = threading.Event()
        self.httpd = None
        self._logged_since = (0, 0, 0)
        self._auth_warned = False
        self._save_warned = False
        self._pending = {}  # 正在翻的句子 -> Event，同一句同时来两次只调一次 API
        self._busy = 0

    # ---------------------------------------------------------- 服务
    def start(self):
        svc = self

        class H(BaseHTTPRequestHandler):
            def log_message(self, *a):
                pass

            def do_GET(self):
                u = urllib.parse.urlparse(self.path)
                if u.path.rstrip("/") != "/translate":
                    self.send_response(404)
                    self.end_headers()
                    return
                q = urllib.parse.parse_qs(u.query, keep_blank_values=True)
                text = (q.get("text") or [""])[0]
                try:
                    res = svc.translate(text)
                    code = 200
                except Exception as e:
                    res, code = str(e), 500
                body = res.encode("utf-8")
                self.send_response(code)
                self.send_header("Content-Type", "text/plain; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)

        try:
            self.httpd = _Server(("127.0.0.1", PORT), H)
        except OSError:
            self.httpd = None
            return False
        threading.Thread(target=self.httpd.serve_forever, daemon=True).start()
        threading.Thread(target=self._autosave, daemon=True).start()
        return True

    def busy(self):
        return self._busy

    def shutdown(self, wait_seconds=0):
        """关之前先等已经发出去的请求回来（已经付了钱），再存盘"""
        end = time.time() + wait_seconds
        while self._busy and time.time() < end:
            time.sleep(0.2)
        self.stop.set()
        self.save()
        self.flush_usage()
        if self.httpd:
            try:
                self.httpd.shutdown()
                self.httpd.server_close()
            except Exception:
                pass

    def _autosave(self):
        while not self.stop.wait(10):
            self.save()

    def save(self):
        """返回 True = 硬盘上已经是最新的；False = 有新译文没存进去"""
        if self.broken:
            return True  # 缓存文件坏了的时候服务没在翻，内存里没有新东西
        with self.file_lock:
            with self.lock:
                if not self.dirty:
                    return True
                data = dict(self.cache)
                meta = dict(self.meta)
                n, self.dirty = self.dirty, 0
            try:
                core.write_json(CACHE_PATH, data, indent=1)
                core.write_json(META_PATH, meta, indent=1)
                self._save_warned = False
                return True
            except Exception as e:
                with self.lock:
                    self.dirty += n  # 下次再试（条数也保留，关工具时提示才准）
                if not self._save_warned:
                    self._save_warned = True
                    self.log("Unity 翻译缓存保存失败（%s），会自动重试；一直失败的话检查工具文件夹是不是只读" % e)
                return False

    def unsaved(self):
        """还没存进硬盘的新译文条数（大概）"""
        with self.lock:
            return self.dirty

    def delete_translations(self, root, model):
        """删某个模型翻的句子：直接在内存缓存里删再整份写盘。
        内存里的缓存比硬盘上的全（还没来得及自动保存的也在），所以不用重新读盘，不会丢东西"""
        if self.broken:
            raise RuntimeError(self.broken)
        with self.file_lock:
            p, lines = _game_entries(root)
            keep, gone = [], 0
            with self.lock:
                if self._pending:
                    # 有请求在路上：删完它回来又会把译文写回去。检查和删除在同一把锁里，中间插不进新请求
                    raise RuntimeError("游戏正在请求翻译（%d 句在路上），先关掉游戏再删" % len(self._pending))
                for line in lines:
                    k, v = _split_line(line) if not line.startswith("//") else (None, None)
                    if k is not None:
                        key = _unescape(k)
                        if model is None or self.meta.get(key, core.UNKNOWN_MODEL) == model:
                            gone += 1
                            self.cache.pop(key, None)
                            self.meta.pop(key, None)
                            continue
                    keep.append(line)
                data, meta = dict(self.cache), dict(self.meta)
                was_dirty, self.dirty = self.dirty, 0
            if not gone:
                with self.lock:
                    self.dirty += was_dirty
                return 0
            try:
                with open(p, "w", encoding="utf-8") as f:
                    f.write("\n".join(keep) + ("\n" if keep else ""))
                core.write_json(CACHE_PATH, data, indent=1)
                core.write_json(META_PATH, meta, indent=1)
            except Exception:
                with self.lock:
                    self.dirty += was_dirty + 1  # 内存里已经删了，自动保存会再写一次
                raise
            return gone

    def set_game(self, title):
        self.flush_usage()
        self.current_game = title

    def flush_usage(self):
        now = (self.usage.hit, self.usage.miss, self.usage.out)
        if now != self._logged_since:
            core.log_usage("[Unity] " + (self.current_game or "未知游戏"), self.cfg, self._logged_since, now)
            self._logged_since = now

    # ---------------------------------------------------------- 翻译一句
    def translate(self, text):
        if not text or not text.strip():
            return text
        if self.broken:
            raise RuntimeError("translation cache file is broken, see the tool window")
        while True:
            with self.lock:
                hit = self.cache.get(text)
                if hit is not None:
                    return hit
                ev = self._pending.get(text)
                if ev is None:
                    ev = self._pending[text] = threading.Event()
                    break
            ev.wait(120)  # 同一句别人正在翻，等它的结果
            with self.lock:
                hit = self.cache.get(text)
            if hit is not None:
                return hit
            raise RuntimeError("translation failed")
        try:
            with self.lock:
                self._busy += 1
            return self._translate_new(text)
        finally:
            with self.lock:
                self._busy -= 1
                self._pending.pop(text, None)
            ev.set()

    def _translate_new(self, text):
        cfg = dict(self.cfg)
        src_lang = cfg.get("unity_from_lang") or "en"
        if not need_translate(text, src_lang):
            return text
        if not cfg.get("api_key"):
            raise RuntimeError("tool has no API key")
        cfg["json_mode"] = False
        p = UNITY_PROMPT % _SAME_RULE.get(src_lang, _DEFAULT_SAME_RULE)
        gl = {k: v for k, v in (cfg.get("glossary") or {}).items() if k and v}
        if gl:
            p += "\n\n专有名词固定译法（必须遵守）：\n" + "\n".join("- %s → %s" % (k, v) for k, v in gl.items())
        if cfg.get("extra_prompt"):
            p += "\n\n额外要求：" + cfg["extra_prompt"]
        msgs = [{"role": "system", "content": p}, {"role": "user", "content": text}]
        want = core.Counter(UNITY_TOKEN_RE.findall(text))
        out = None
        for _ in range(2):
            try:
                r = core.call_with_retry(cfg, msgs, self.usage, self.stop, tries=3).strip()  # 关工具时不再重试
            except core.AuthError as e:
                if not self._auth_warned:
                    self._auth_warned = True
                    self.log("Unity 翻译：接口拒绝了请求（%s），检查 key / 余额 / 模型名。" % e)
                raise
            if len(r) >= 2 and r[0] in "\"“「'" and r[-1] in "\"”」'" and text.strip()[:1] not in "\"“「'":
                r = r[1:-1].strip()
            if r and core.Counter(UNITY_TOKEN_RE.findall(r)) == want:
                out = r
                break
        if out is None:
            self.failed += 1
            raise RuntimeError("translation failed")
        lead = text[: len(text) - len(text.lstrip())]
        trail = text[len(text.rstrip()):]
        out = lead + out + trail
        with self.lock:
            self.cache[text] = out
            self.meta[text] = cfg.get("model") or "?"
            self.dirty += 1
            self.count += 1
        return out


# ============================================================== 按模型删 Unity 译文

def _unescape(s):
    out, i = [], 0
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            n = s[i + 1]
            out.append({"n": "\n", "r": "\r", "t": "\t"}.get(n, n))
            i += 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


def _split_line(line):
    i = 0
    while i < len(line):
        if line[i] == "\\":
            i += 2
            continue
        if line[i] == "=":
            return line[:i], line[i + 1:]
        i += 1
    return None, None


def _game_entries(root):
    p = translation_file(root)
    try:
        with open(p, "r", encoding="utf-8-sig", errors="replace") as f:
            lines = f.read().splitlines()
    except OSError:
        return p, []
    return p, lines


def model_counts(root):
    meta = core.read_json(META_PATH, {}) or {}
    p, lines = _game_entries(root)
    c = core.Counter()
    for line in lines:
        if line.startswith("//"):
            continue
        k, v = _split_line(line)
        if k is None:
            continue
        c[meta.get(_unescape(k), core.UNKNOWN_MODEL)] += 1
    return c


# 删除译文：见 TranslateService.delete_translations（要和自动保存走同一把锁，所以放在服务里）
